# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title mode2(NumericVector x) function
#' @description Function mode2() determines the most frequently occurring value in an integer
#' vector (mode). If the mode is ambiguous (e.g. for 1, 2, 2, 2, 3, 3, 1, 3),
#' function returns any mode.
#'
#' @return An integer value - the mode of the input integer vector x.
#'
#' @export
mode2 <- function(x) {
    .Call('mypackage_mode2', PACKAGE = 'mypackage', x)
}

#' @title simplify2array2(List x) function
#' @description Function simplify2array2() converts a list containing numeric vectors into a matrix.
#'
#' @return A matrix which columns are equivalent with elements of a imput list.
#'
#' @export
simplify2array2 <- function(x) {
    .Call('mypackage_simplify2array2', PACKAGE = 'mypackage', x)
}

